services:
  - type: worker         # web → worker 로 변경
    name: discord-bot
    env: docker
    plan: starter        # $7/월 (Background Worker 최소 플랜)
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    region: singapore
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: TZ
        value: Asia/Seoul
